FROM python:3.11-slim

ARG CLIO_API_KEY
ARG CLIO_BASE_URL=https://api.novita.ai/openai
ARG CLIO_MODEL=google/gemma-4-31b-it
ARG CLIO_VERIFY_MODEL=google/gemma-4-31b-it
ARG CLIO_CAPTION_MODEL=google/gemma-4-31b-it
ARG CLIO_VISION_MODEL=
ARG CLIO_PIPELINE=verified5-champion
ARG SWIFTCLIP_FRAME_STRATEGY=anchors
ARG SWIFTCLIP_FRAME_COUNT=4
ARG SWIFTCLIP_FRAME_WIDTH=768
ARG CLIO_GRID_INPUT=0
ARG CLIO_ALLOW_NON_GEMMA_CAPTION=0
ARG SWIFTCLIP_PARALLEL=2
ARG CLIO_RATE_LIMIT_RETRIES=3
ARG CLIO_REQUEST_TIMEOUT=50

ENV PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    CLIO_API_KEY=${CLIO_API_KEY} \
    CLIO_BASE_URL=${CLIO_BASE_URL} \
    CLIO_MODEL=${CLIO_MODEL} \
    CLIO_VERIFY_MODEL=${CLIO_VERIFY_MODEL} \
    CLIO_CAPTION_MODEL=${CLIO_CAPTION_MODEL} \
    CLIO_VISION_MODEL=${CLIO_VISION_MODEL} \
    CLIO_ENFORCE_NOVITA=1 \
    CLIO_FAST_MODE=1 \
    CLIO_PIPELINE=${CLIO_PIPELINE} \
    CLIO_REQUEST_TIMEOUT=${CLIO_REQUEST_TIMEOUT} \
    CLIO_RATE_LIMIT_RETRIES=${CLIO_RATE_LIMIT_RETRIES} \
    SWIFTCLIP_FRAME_STRATEGY=${SWIFTCLIP_FRAME_STRATEGY} \
    SWIFTCLIP_FRAME_COUNT=${SWIFTCLIP_FRAME_COUNT} \
    SWIFTCLIP_FRAME_WIDTH=${SWIFTCLIP_FRAME_WIDTH} \
    CLIO_GRID_INPUT=${CLIO_GRID_INPUT} \
    CLIO_ALLOW_NON_GEMMA_CAPTION=${CLIO_ALLOW_NON_GEMMA_CAPTION} \
    SWIFTCLIP_PARALLEL=${SWIFTCLIP_PARALLEL} \
    SWIFTCLIP_CLIP_TIMEOUT=180

RUN apt-get update -y \
 && apt-get install -y --no-install-recommends ffmpeg ca-certificates tesseract-ocr \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app ./app
RUN mkdir -p /input /output

CMD ["python", "-m", "app.visual", "/input/tasks.json", "/output/results.json"]
